PROGS=part1 part2 part3 part4 part5

ALL: ${PROGS}

clean:
	rm -f *.o ${PROGS}

part1: part1.o bits.o

part2: part2.o bits.o

part3: part3.o bits.o

part4: part4.o bits.o

part5: part5.o bits.o

bits.o: bits.c bits.h
