# makefile -- rules to build OSP workshop C
# Dr Evan Crawford (e.crawford@westernsydney.edu.au)
# COMP 30015 Operating Systems Programming
# Practical Case Study C
# This is the sample file
#
# to use simply type "make"
# this will build the main executable caseE
#
# note, this is a configuration file for the MAKE utility
# do not try to run it directly
# if typing up the file, the indented lines need to be indented
# with TABS not spaces.


all: caseE

caseE: main.o fs.o
	$(CC) -o $@ $^
